### ISSUE TITLE
Deducting HP in an actor's token HP bar while the actor has temp HP kills them

### ISSUE THREAD

**Issue by joshjlewis93** [zeel01/input-expressions#2]
While an actor has temporary HP, entering a negative value in to the token's HP bar should deduct the appropriate amount from the temp HP and then carry over to the real HP. With IE active, entering a negative value while the actor has temporary HP removes all the temporary HP _and_ reduces their real HP to 0.

Steps to reproduce:

1) Set a token's bar to represent the actor's HP
2) Add temporary HP to the actor
3) Right-click the token and enter a negative integer in to the HP box  (eg. -5)

**Comment by zeel01** [comment]
Caused by a 5e bug.
